/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AtCoderIcon: typeof import('./src/components/icons/AtCoderIcon.vue')['default']
    CodeforcesIcon: typeof import('./src/components/icons/CodeforcesIcon.vue')['default']
    Link: typeof import('./src/components/Link.vue')['default']
    LuoguIcon: typeof import('./src/components/icons/LuoguIcon.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NowcoderIcon: typeof import('./src/components/icons/NowcoderIcon.vue')['default']
    NSpace: typeof import('naive-ui')['NSpace']
    NTransfer: typeof import('naive-ui')['NTransfer']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VJudgeIcon: typeof import('./src/components/icons/VJudgeIcon.vue')['default']
  }
}
