// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AtCoder: typeof import('./src/components/icons/AtCoder.vue')['default']
    Codeforces: typeof import('./src/components/icons/Codeforces.vue')['default']
    GitHub: typeof import('./src/components/icons/GitHub.vue')['default']
    Link: typeof import('./src/components/Link.vue')['default']
    Luogu: typeof import('./src/components/icons/Luogu.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    Nowcoder: typeof import('./src/components/icons/Nowcoder.vue')['default']
    NSpace: typeof import('naive-ui')['NSpace']
    NTransfer: typeof import('naive-ui')['NTransfer']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Website: typeof import('./src/components/icons/Website.vue')['default']
  }
}
