<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    x="0px"
    y="0px"
    width="24px"
    height="24px"
    viewBox="0 0 24 24"
    xml:space="preserve"
  >
    <image
      id="image0"
      width="24"
      height="24"
      x="0"
      y="0"
      href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVlidH////q7/l6mdfM2PDg5/ajuONvkdStwOb19/yEodrW4POYsOCUoOB9AAAAAWJLR0QB/wIt3gAAAAd0SU1FB+cCCwYsA87hE10AAAA6SURBVAjXY2AgBQgKGTiKGjCIMYgVdcwqdQAzuh04BIAMQVFrCEOMgWNW6Y7pMkAGg6OosWI4STYAAKKYCWTcLk1hAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIzLTAyLTExVDA2OjQ0OjAzKzAwOjAwQKGBKQAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMy0wMi0xMVQwNjo0NDowMyswMDowMDH8OZUAAAAodEVYdGRhdGU6dGltZXN0YW1wADIwMjMtMDItMTFUMDY6NDQ6MDMrMDA6MDBm6RhKAAAAAElFTkSuQmCC"
    />
  </svg>
</template>
